let Items = [
  {
    id: 0,
    name: "Pizza",
    src: "https://png.pngtree.com/png-vector/20230321/ourmid/pngtree-modern-kitchen-food-box-italian-pizza-png-image_6651521.png",
    mrp: 200,
    quantDivide: true,
    quantity: 0,
    options: [{ Regular: 200, Medium: 400 }],
    isVeg: true,
  },
  {
    id: 1,
    name: "Burger",
    src: "https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-burger-food-png-free-download-png-image_10199386.png",
    mrp: 120,
    quantDivide: false,
    quantity: 0,
    options: [{ Half: 120, Full: 200 }],
    isVeg: true,
  },
  {
    id: 2,
    name: "Momos",
    src: "https://png.pngtree.com/png-clipart/20230429/original/pngtree-delicious-momos-with-chutney-free-psd-png-image_9121929.png",
    mrp: 150,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 120, Full: 240 }],
    isVeg: true,
  },
  {
    id: 3,
    name: "Noodles",
    src: "https://assets-global.website-files.com/6305f7d600c9842969920a58/63c77db214fd77b1779eb9bd_yK9ECV7smdhbLMzv4p77q11j7-KUeInv-mLqo7uBpBg.png",
    mrp: 300,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 100, Full: 200 }],
    isVeg: true,
  },
  {
    id: 4,
    name: "HakkaNoodles",
    src: "https://www.pngall.com/wp-content/uploads/5/Chinese-Noodles-PNG-Download-Image.png",
    mrp: 340,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 150, Full: 250 }],
    isVeg: true,
  },
  {
    id: 5,
    name: "CheesePizza",
    src: "https://static.vecteezy.com/system/resources/previews/030/809/379/original/cheese-pizza-no-background-free-png.png",
    mrp: 400,
    quantDivide: false,
    quantity: 0,
    options: [{ Regular: 300, Medium: 500 }],
    isVeg: true,
  },
  {
    id: 6,
    name: "FriedRice",
    src: "https://png.pngtree.com/png-clipart/20211010/original/pngtree-photo-of-kimchi-fried-rice-snack-hot-food-lifestyle-png-image_6849862.png",
    mrp: 400,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 140, Full: 250 }],
    isVeg: true,
  },
  {
    id: 7,
    name: "DalMakhani",
    src: "https://png.pngtree.com/png-clipart/20230903/original/pngtree-dal-makhani-top-view-png-image_10805423.png",
    mrp: 200,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 150, Full: 280 }],
    isVeg: true,
  },
  {
    id: 8,
    name: "Paneer Tikka",
    src: "https://static.vecteezy.com/system/resources/previews/036/498/564/non_2x/ai-generated-paneer-tikka-on-a-white-plate-on-transparent-background-png.png",
    mrp: 250,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 250, Full: 400 }],
    isVeg: true,
  },
  {
    id: 9,
    name: "Chole Bhature",
    src: "https://static.vecteezy.com/system/resources/previews/036/627/131/original/ai-generated-realistic-chole-bhature-on-transparent-background-png.png",
    mrp: 180,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 120, Full: 230 }],
    isVeg: true,
  },
  {
    id: 10,
    name: "Butter Chicken",
    src: "https://static.vecteezy.com/system/resources/previews/025/270/174/non_2x/butter-chicken-with-ai-generated-free-png.png",
    mrp: 350,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 250, Full: 420 }],
    isVeg: false,
  },
  {
    id: 11,
    name: "Samosa",
    src: "https://static.vecteezy.com/system/resources/previews/024/106/549/original/tasty-crispy-samosa-on-transparent-background-png.png",
    mrp: 50,
    quantDivide: false,
    quantity: 0,
    options: [{ Half: 20, Full: 40 }],
    isVeg: true,
  },
  {
    id: 12,
    name: "Gulab Jamun",
    src: "https://png.pngtree.com/png-clipart/20231018/original/pngtree-diwali-gulab-jamun-png-image_13343607.png",
    mrp: 100,
    quantDivide: false,
    quantity: 0,
    options: [{ Half: null, Full: null }],
    isVeg: true,
  },
  {
    id: 13,
    name: "Pav Bhaji",
    src: "https://5.imimg.com/data5/SELLER/Default/2023/3/294873947/JH/MF/GR/101335061/indian-bhaji-500x500.png",
    mrp: 150,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 160, Full: 320 }],
    isVeg: true,
  },
  {
    id: 14,
    name: "Tandoori Chicken",
    src: "https://static.vecteezy.com/system/resources/previews/025/229/917/original/tasty-tandoori-chicken-plate-isolated-on-transparent-background-png.png",
    mrp: 300,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 340, Full: 450 }],
    isVeg: false,
  },
  {
    id: 15,
    name: "Biryani",
    src: " https://png.pngtree.com/png-clipart/20230521/original/pngtree-vegetable-biryani-png-image_9166733.png",
    mrp: 250,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 220, Full: 330 }],
    isVeg: true,
  },
  {
    id: 16,
    name: "Paneer Masala",
    src: "https://png.pngtree.com/png-clipart/20230912/original/pngtree-paneer-butter-masala-png-image_11051765.png",
    mrp: 220,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 220, Full: 300 }],
    isVeg: true,
  },
  {
    id: 17,
    name: "Spring Rolls",
    src: "https://static.vecteezy.com/system/resources/previews/025/222/148/original/chinese-traditional-spring-rolls-isolated-on-transparent-background-png.png",
    mrp: 180,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 80, Full: 150 }],
    isVeg: true,
  },
  {
    id: 18,
    name: "Chicken Kebab",
    src: "https://static.vecteezy.com/system/resources/previews/024/501/008/non_2x/chicken-kabab-chicken-tikka-kabab-image-with-transparent-background-free-ai-generative-free-png.png",
    mrp: 280,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 200, Full: 340 }],
    isVeg: false,
  },
  {
    id: 19,
    name: "Momos",
    src: "https://png.pngtree.com/png-vector/20240208/ourmid/pngtree-nepal-food-momo-dumpling-png-image_11719797.png",
    mrp: 150,
    quantDivide: true,
    quantity: 0,
    options: [{ Half: 100, Full: 180 }],
    isVeg: true,
  },
];

export default Items;
